// <auto-generated />
using EFTechCommerce;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebProject.Migrations
{
    [DbContext(typeof(TechCommerceContext))]
    partial class TechCommerceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("FavouriteDTOModel.FavouriteDTO", b =>
                {
                    b.Property<int>("FavouriteDTOId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductLink")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FavouriteDTOId");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("ProductDTOModel.ProductDTO", b =>
                {
                    b.Property<int>("ProductDTOId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductURL")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductDTOId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("UserDTOModel.UserDTO", b =>
                {
                    b.Property<int>("UserDTOId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserDTOId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
